---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: isolation-proxy
    createdBy: EKS-Control
    owner: TIO
  name: isolation-proxy
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      deployment: isolation-proxy
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 0%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: isolation-proxy
        createdBy: EKS-Control
        deployment: isolation-proxy
        owner: TIO
    spec:
      containers:
      - env:
        - name: ENVCOLOR
          value: isolation-proxy-STAGE
        - name: OTHERCOLORURL
          value: http://test-product/index-other.shtml
        image: thetemplateblog/squid-proxy:latest
        imagePullPolicy: Always
        livenessProbe:
          tcpSocket:
            port: 3128
          initialDelaySeconds: 5
          periodSeconds: 60
        name: isolation-proxy
        ports:
        - containerPort: 3128
          protocol: TCP
        readinessProbe:
          tcpSocket:
            port: 3128
          initialDelaySeconds: 5
          periodSeconds: 60
        resources:
          limits:
            cpu: 256m
            memory: 256Mi
          requests:
            cpu: 10m
            memory: 10Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: isolation-proxy.prodcopy.eols.health.elsevier.com
    service.beta.kubernetes.io/aws-load-balancer-access-log-emit-interval: "60"
    service.beta.kubernetes.io/aws-load-balancer-access-log-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-access-log-s3-bucket-name: eols-nonprod-logging-255310279045-us-east-1
    service.beta.kubernetes.io/aws-load-balancer-access-log-s3-bucket-prefix: eols-eks-prodcopy/stage/isolation-proxy/external-ingress
    service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: kubernetes.io/cluster/eols-eks-prodcopy=owned,
      Product=eols, Environment=stage, SubProduct=isolation-proxy, Role=isolation-proxy_loadbalancer,
      Orchestration=kubernetes, Name=eols.stage.isolation-proxy_loadbalancer.external_ingress,
      Description=external_ingress, CostCode=21708, Contact=j.gudknecht@elsevier.com,
      cpm backup=no-backup
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
  labels:
    app: isolation-proxy
    createdBy: EKS-Control
    owner: TIO
  name: isolation-proxy-external-ingress
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  loadBalancerSourceRanges: [
    "10.76.64.0/18",
    "10.184.28.0/22",
    "10.208.70.0/23",
    "10.208.68.0/23",
    "10.88.36.0/23",
    "10.153.64.0/19",
    "10.153.128.0/19",
    "10.153.152.0/22",
    "10.159.0.0/18",
    "172.29.16.0/20",
    "172.28.224.0/19",
    "172.29.48.0/20",
    "172.28.96.0/19",
    "172.29.112.0/20",
    "10.179.19.23/32",
    "10.179.19.75/32",
    "10.149.90.0/24"
  ]
  ports:
  - port: 8008
    protocol: TCP
    targetPort: 3128
  selector:
    app: isolation-proxy
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: isolation-proxy
    createdBy: EKS-Control
    owner: TIO
  name: isolation-proxy
  namespace: default
spec:
  ports:
  - port: 8008
    protocol: TCP
    targetPort: 3128
  selector:
    app: isolation-proxy
  sessionAffinity: None
  type: ClusterIP
