version: '2'

services:
  squid:
    image: ubuntu/squid:edge
    ports:
      - '3128:3128'
    volumes:
      - 'squid_cache:/var/spool/squid'
      - 'squid_logs:/var/log/squid'
volumes:
  squid_cache:
  squid_logs:
